# .github/workflows/update-prices.yml
name: Ejecutar Scrapers Diario

on:
  schedule:
    - cron: '0 8 * * *'  # Todos los días a las 08:00 UTC
  workflow_dispatch:

jobs:
  run-scrapers:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar Chromedriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          wget -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip || wget -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/136.0.7103.113/chromedriver_linux64.zip
          unzip /tmp/chromedriver_linux64.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Ejecutar updater.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python updater.py
